### ISSUE TITLE
Error whilst creating a physical condition

### ISSUE THREAD

**Issue by sfolsom** [rjyounes/vitrolib#188]
Recieved the following when adding a physical condition to http://vitrolib-arm.ld4p.library.cornell.edu/individual/n5371 "There was an error in the system.

Error message: java.lang.Exception: Errors processing required N3. The EditConfiguration should be setup so that if a submission passes validation, there will not be errors in the required N3. [line: 1, col: 580] Out of place: [VAR:object] N3: @prefix arm: <https://w3id.org/arm/core/ontology/0.1/> . @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> . @prefix bib: <http://bibliotek-o.org/ontology/> . @prefix bibframe: <http://id.loc.gov/ontologies/bibframe/> . @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> . @prefix dcterms: <http://purl.org/dc/terms/> . @prefix lexvo: <http://lexvo.org/id/iso639-3/> . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n5371> <https://w3id.org/arm/core/ontology/0.1/hasPhysicalCondition> <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> . ?object rdf:type arm:PhysicalCondition . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> rdf:value "Divet in the bottom right of front cover"^^<http://www.w3.org/2001/XMLSchema#string> . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> rdfs:label "Divet in the bottom right of front cover"^^<http://www.w3.org/2001/XMLSchema#string> .

Stack trace (full trace available in the vivo log): java.lang.Error: java.lang.Exception: Errors processing required N3. The EditConfiguration should be setup so that if a submission passes validation, there will not be errors in the required N3. [line: 1, col: 580] Out of place: [VAR:object] N3: @prefix arm: <https://w3id.org/arm/core/ontology/0.1/> . @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> . @prefix bib: <http://bibliotek-o.org/ontology/> . @prefix bibframe: <http://id.loc.gov/ontologies/bibframe/> . @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> . @prefix dcterms: <http://purl.org/dc/terms/> . @prefix lexvo: <http://lexvo.org/id/iso639-3/> . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n5371> <https://w3id.org/arm/core/ontology/0.1/hasPhysicalCondition> <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> . ?object rdf:type arm:PhysicalCondition . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> rdf:value "Divet in the bottom right of front cover"^^<http://www.w3.org/2001/XMLSchema#string> . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> rdfs:label "Divet in the bottom right of front cover"^^<http://www.w3.org/2001/XMLSchema#string> . at edu.cornell.mannlib.vitro.webapp.edit.n3editing.controller.ProcessRdfFormController.processRequest(ProcessRdfFormController.java:95) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doGet(FreemarkerHttpServlet.java:106) at javax.servlet.http.HttpServlet.service(HttpServlet.java:621) at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) at edu.cornell.mannlib.vitro.webapp.controller.VitroHttpServlet.service(VitroHttpServlet.java:71) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doNonDisplayPage(PageRoutingFilter.java:108) at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doFilter(PageRoutingFilter.java:99) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.ClickjackFilter.doFilter(ClickjackFilter.java:31) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.RequestModelsPrep.doFilter(RequestModelsPrep.java:56) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.URLRewriterFilter.doFilter(URLRewriterFilter.java:38) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.JSessionStripFilter.doFilter(JSessionStripFilter.java:61) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.produceBasicResponse(CachingResponseFilter.java:319) at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.doFilter(CachingResponseFilter.java:113) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.i18n.selection.LocaleSelectionFilter.doFilter(LocaleSelectionFilter.java:62) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:34) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.SessionTimeoutLimitingFilter.doFilter(SessionTimeoutLimitingFilter.java:39) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.StartupStatusDisplayFilter.doFilter(StartupStatusDisplayFilter.java:64) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.Exception: Errors processing required N3. The EditConfiguration should be setup so that if a submission passes validation, there will not be errors in the required N3. [line: 1, col: 580] Out of place: [VAR:object] N3: @prefix arm: <https://w3id.org/arm/core/ontology/0.1/> . @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> . @prefix bib: <http://bibliotek-o.org/ontology/> . @prefix bibframe: <http://id.loc.gov/ontologies/bibframe/> . @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> . @prefix dcterms: <http://purl.org/dc/terms/> . @prefix lexvo: <http://lexvo.org/id/iso639-3/> . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n5371> <https://w3id.org/arm/core/ontology/0.1/hasPhysicalCondition> <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> . ?object rdf:type arm:PhysicalCondition . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> rdf:value "Divet in the bottom right of front cover"^^<http://www.w3.org/2001/XMLSchema#string> . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> rdfs:label "Divet in the bottom right of front cover"^^<http://www.w3.org/2001/XMLSchema#string> . at edu.cornell.mannlib.vitro.webapp.edit.n3editing.VTwo.ProcessRdfForm.parseN3ToRDF(ProcessRdfForm.java:305) at edu.cornell.mannlib.vitro.webapp.edit.n3editing.VTwo.ProcessRdfForm.parseN3ToChange(ProcessRdfForm.java:262) at edu.cornell.mannlib.vitro.webapp.edit.n3editing.VTwo.ProcessRdfForm.createNewStatements(ProcessRdfForm.java:122) at edu.cornell.mannlib.vitro.webapp.edit.n3editing.VTwo.ProcessRdfForm.process(ProcessRdfForm.java:84) at edu.cornell.mannlib.vitro.webapp.edit.n3editing.controller.ProcessRdfFormController.processRequest(ProcessRdfFormController.java:92) ... 53 more

Caused by: java.lang.Exception: Errors processing required N3. The EditConfiguration should be setup so that if a submission passes validation, there will not be errors in the required N3. [line: 1, col: 580] Out of place: [VAR:object] N3: @prefix arm: <https://w3id.org/arm/core/ontology/0.1/> . @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> . @prefix bib: <http://bibliotek-o.org/ontology/> . @prefix bibframe: <http://id.loc.gov/ontologies/bibframe/> . @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> . @prefix dcterms: <http://purl.org/dc/terms/> . @prefix lexvo: <http://lexvo.org/id/iso639-3/> . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n5371> <https://w3id.org/arm/core/ontology/0.1/hasPhysicalCondition> <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> . ?object rdf:type arm:PhysicalCondition . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> rdf:value "Divet in the bottom right of front cover"^^<http://www.w3.org/2001/XMLSchema#string> . <http://vitrolib-arm.ld4p.library.cornell.edu/individual/n205> rdfs:label "Divet in the bottom right of front cover"^^<http://www.w3.org/2001/XMLSchema#string> . at edu.cornell.mannlib.vitro.webapp.edit.n3editing.VTwo.ProcessRdfForm.parseN3ToRDF(ProcessRdfForm.java:305) at edu.cornell.mannlib.vitro.webapp.edit.n3editing.VTwo.ProcessRdfForm.parseN3ToChange(ProcessRdfForm.java:262) at edu.cornell.mannlib.vitro.webapp.edit.n3editing.VTwo.ProcessRdfForm.createNewStatements(ProcessRdfForm.java:122) at edu.cornell.mannlib.vitro.webapp.edit.n3editing.VTwo.ProcessRdfForm.process(ProcessRdfForm.java:84) at edu.cornell.mannlib.vitro.webapp.edit.n3editing.controller.ProcessRdfFormController.processRequest(ProcessRdfFormController.java:92) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doGet(FreemarkerHttpServlet.java:106) at javax.servlet.http.HttpServlet.service(HttpServlet.java:621) at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) at edu.cornell.mannlib.vitro.webapp.controller.VitroHttpServlet.service(VitroHttpServlet.java:71) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doNonDisplayPage(PageRoutingFilter.java:108) at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doFilter(PageRoutingFilter.java:99) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.ClickjackFilter.doFilter(ClickjackFilter.java:31) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.RequestModelsPrep.doFilter(RequestModelsPrep.java:56) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.URLRewriterFilter.doFilter(URLRewriterFilter.java:38) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.JSessionStripFilter.doFilter(JSessionStripFilter.java:61) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.produceBasicResponse(CachingResponseFilter.java:319) at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.doFilter(CachingResponseFilter.java:113) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.i18n.selection.LocaleSelectionFilter.doFilter(LocaleSelectionFilter.java:62) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:34) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.SessionTimeoutLimitingFilter.doFilter(SessionTimeoutLimitingFilter.java:39) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at edu.cornell.mannlib.vitro.webapp.filters.StartupStatusDisplayFilter.doFilter(StartupStatusDisplayFilter.java:64) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)"

**Comment by sfolsom** [comment]
Have since been able to create physical condition statements.
