### ISSUE TITLE
ClassNotFoundException on N3TransitionToV2Mapping

### ISSUE THREAD

**Issue by daveneiman** [rjyounes/vitrolib#35]
When attempting to create a new individual on the admin page received the following stack trace in log. Could not find class in either Vitro or Vitrolib. Functionality was not impaired.

2017-01-09 14:17:01,522 ERROR [JspToGeneratorMapping] could not load VIVO jsp mappings
java.lang.ClassNotFoundException: edu.cornell.mannlib.vitro.webapp.edit.n3editing.N3TransitionToV2Mapping
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1139)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at edu.cornell.mannlib.vitro.webapp.edit.n3editing.VTwo.JspToGeneratorMapping.<clinit>(JspToGeneratorMapping.java:49)
	at edu.cornell.mannlib.vitro.webapp.edit.n3editing.configuration.generators.DefaultObjectPropertyFormGenerator.getEditConfiguration(DefaultObjectPropertyFormGenerator.java:102)
	at edu.cornell.mannlib.vitro.webapp.edit.n3editing.controller.EditRequestDispatchController.makeEditConfigurationVTwo(EditRequestDispatchController.java:417)
	at edu.cornell.mannlib.vitro.webapp.edit.n3editing.controller.EditRequestDispatchController.setupEditConfiguration(EditRequestDispatchController.java:173)
	at edu.cornell.mannlib.vitro.webapp.edit.n3editing.controller.EditRequestDispatchController.processRequest(EditRequestDispatchController.java:94)
	at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doGet(FreemarkerHttpServlet.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)

**Comment by hudajkhan** [comment]
This should have been resolved and we can reopen if need be.
